version: 0.2

phases:
  install:
    commands:
      - echo Installing nginx
      - sudo apt-get update
      - sudo apt-get remove -y nginx
      - sudo apt-get install -y nginx
  build:
    commands:
      - echo Build phase started on `date`
      - echo Adding files to nginx root directory
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo Checking nginx service status
      - sudo systemctl status nginx || sudo journalctl -u nginx
artifacts:
  files:
    - index.html

